services:
  # Backend API service
  - type: web
    name: whatsapp-clone-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        fromService:
          type: web
          name: whatsapp-clone-frontend
          envVarKey: RENDER_EXTERNAL_URL

  # Frontend service
  - type: web
    name: whatsapp-clone-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: whatsapp-clone-api
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html